## **Ejercicio Operaciones con Arrays NumPy**

In [9]:
import numpy as np

### 1. Inicializa un array NumPy llamado matriz con una forma de (3, 3) que contenga los números enteros del 1 al 9 (inclusive) dispuestos en filas, usando la función correspondiente. Es decir, la matriz debe verse así:


      [[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]]

In [22]:
matriz_ejercicio = np.arange(1,10).reshape(3,3)
print(matriz_ejercicio)	

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2. Accede e imprime el elemento en la segunda fila y la tercera columna de la matriz.

In [7]:
print(matriz_ejercicio[1,2])

6


### 3. Utiliza una función para crear un nuevo array llamado nuevo_array que contenga los números pares del 10 al 20 (inclusive). Luego, redimensiona este nuevo array a una forma de (2, ?).

In [8]:

nuevo_array = np.arange(10,21,2)

print(nuevo_array)

nuevo_array = nuevo_array.reshape(2,-1)

print(nuevo_array)

[10 12 14 16 18 20]
[[10 12 14]
 [16 18 20]]


### 4. Crea un array NumPy llamado unos que sea una matriz de unos con una forma de (3, 4).

In [11]:
matriz_unos = np.ones((3,4))
print(matriz_unos)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### 5. Redimensiona la matriz unos a una forma de (2, 6) utilizando la función reshape y de (6,2) utilizando resize. ¿Qué diferencia hay?

In [13]:
#con reshape
matriz_unos = matriz_unos.reshape(2,6)

print(matriz_unos)

#con resize

matriz_unos.resize(2,6)

print(matriz_unos)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


La diferencia principal y que se puede observar a simple vista es que con reshape no se modifica la matriz o array original, mientras que resize hace una modificación directa de la matriz o array original

## **Ejercicio: Operaciones de rebanado** 

### 1. Crear una matriz bidimensional (3, 4), con números consecutivos de 1 a 12, con numpy.

In [23]:
matriz_ejercicio2 = np.arange(1,13).reshape(3,4)
print(matriz_ejercicio2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 2. Crear un vector unidimensional, de 4 elementos, que vaya de 10 en 10

In [24]:
vector_10en10 = np.arange(10,41,10)
print(vector_10en10)

[10 20 30 40]


### 3. Rebanado de la matriz:

    Seleccionar la segunda fila completa

    Seleccionar la tercera columna completa

    Seleccionar una submatriz, con las filas 0 y 1 de la matriz original, y las columnas 1 y 2 de la matriz original.

In [25]:
#Rebanado de matriz
# Seleccionar la segunda fila de la matriz
print(matriz_ejercicio2[1,:])

# Seleccionar la tercera columna completa
print(matriz_ejercicio2[:,2])

# Seleccionar la submatriz, con las filas 0 y 1 de la matriz original y las columnas 1 y 2 de la matriz original
print(matriz_ejercicio2[0:2,1:3])

[5 6 7 8]
[ 3  7 11]
[[2 3]
 [6 7]]



### 4. Rebanado del vector:

    Seleccionar los primeros 3 elementos

In [26]:
#seleccionar el vector y solo los primeros 3 elementos
print(vector_10en10[:3])

[10 20 30]
